

<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="refresh" content="5; URL=/index.htm">
<STYLE>.clear { clear: both; } .a { background-color: #111111; } .t { padding: 10px 10px 20px 10px; border: 5px solid #551111; margin: 25px 25px 0px 25px; color: #999999; background-color: #111111; min-width: 30em; } input { font-weight: bold; width:4em; background-color: #A01010; padding: 2px 2px; }.b { padding: 10px; border-left: 5px solid #551111; border-right: 5px solid #551111; border-bottom: 5px solid #551111; margin: 0px 25px 25px 25px; color: #999999;background-color: #111111; min-width: 30em; } select { width:4em; font-weight: bold; background-color: #A01010; padding: 2px 2px; } .c { color: #A01010; font-weight: bold; }h1 { text-align: right; } a:hover, a:active { background-color: red; } .y { color: #FFFF00; font-weight: bold; }a:link, a:visited { background-color: #332222; color: #a07070; border:1px solid red; padding: 5px 10px; margin: none; text-align: center; text-decoration: none; display: inline-block; }button { background-color: #A01010; font-weight: bold; border-radius: 5px; margin: 2px; padding: 4px 8px; }.b1 { float: left; border: 2px solid #551111; background-color: #181818; text-align: center; margin: 5px; padding: 15px; padding-top: 3px; }.gb {  font-weight: bold; font-size: 150%; font-family: 'Times New Roman', Times, serif; width: 60px; height: 50px; padding: 0px; }.bb {  font-weight: bold; font-size: 105%; } .bbh {  font-weight: bold; font-size: 100%; height: 2.1em; }</STYLE></head>
<body bgcolor='#26262A'>
<div class='t'><table width='100%%'><tr><td><b><font size='5'>OnStep</font></b></td><td align='right'><b>OnEsp 1.6c (OnStep 2.22k)</b></td></tr></table><a href='/index.htm' style='background-color: #552222;'>Status</a><a href='/control.htm'>Control</a><a href='/pec.htm'>PEC</a><a href='/settings.htm'>Settings</a><a href='/configuration.htm'>Configuration</a><a href='/wifi.htm'>WiFi</a><br /></div><div class='b'>
<div style='width: 27em;'><b>Site:</b><br />&nbsp;&nbsp;<span id="datetime"></span> UT (web browser)<script> function pad(num, size) { var s = '000000000' + num; return s.substr(s.length-size); }var now = new Date(); document.getElementById('datetime').innerHTML = (now.getUTCMonth()+1)+'/'+pad(now.getUTCDate().toString(),2)+'/'+pad(now.getUTCFullYear().toString().substr(-2),2)+' '+pad(now.getUTCHours().toString(),2)+':'+pad(now.getUTCMinutes().toString(),2)+':'+pad(now.getUTCSeconds().toString(),2); </script><br />
&nbsp;&nbsp;<font class='c'>08/11/19</font>&nbsp;<font class='c'>20:26:17</font>&nbsp;UT&nbsp;(<font class='c'>18:47:04</font>&nbsp; LST)<br />&nbsp;&nbsp;Long. = <font class='c'>-015*11</font>, Lat. = <font class='c'>+50*43</font><br />&nbsp;&nbsp;Temperature: <font class='c'>10.0</font>&deg;C<br />&nbsp;&nbsp;Barometric Pressure: <font class='c'>1010.0</font>mb<br />&nbsp;&nbsp;Relative Humidity: <font class='c'>70.0</font>%<br />&nbsp;&nbsp;Dew Point Temperature: <font class='c'>4.0</font>&deg;C<br /><br /><b>Coordinates:</b><br />&nbsp;&nbsp;Current: &alpha;=<font class='c'>06:47:03.6511</font>, &delta;=<font class='c'>+89*59:10.246</font><br />&nbsp;&nbsp;Target:&nbsp;&nbsp; &alpha;=<font class='c'>00:00:00.0000</font>, &delta;=<font class='c'>+00*00:00.000</font><br />&nbsp;&nbsp;Pier Side=<font class='c'>None</font> (meridian flips <font class='c'>On</font>)<br /><br /><b>Polar Alignment:</b><br />&nbsp;&nbsp;&#x25c4; <font class='c'>0</font>" &nbsp; &#x25b2; <font class='c'>0</font>" &nbsp;(Mount relative to NCP)<br /><br /><b>Operations:</b><br />&nbsp;&nbsp;Parking: <font class='c'>Not Parked </font>(<font class="c">At Home</font>)<font class="c"></font><br />&nbsp;&nbsp;Tracking: <font class='c'>Off </font><br />&nbsp;&nbsp;Tracking Rate: <font class="c">0.000</font>Hz<br />&nbsp;&nbsp;Maximum slew speed: <font class='c'>1.9</font>&deg;/s<br /><br /><b>State:</b><br />&nbsp;&nbsp;Axis1 Driver: <font class='c'>Standstill</font><br />&nbsp;&nbsp;Axis2 Driver: <font class='c'>Standstill</font><br />&nbsp;&nbsp;Last Error: <font class='c'>None</font><br />&nbsp;&nbsp;Workload: <font class='c'>12%</font><br /></div><br class="clear" />
</div></body></html>

